Update LOCALIZE.md
maqsoftware/Simple-Class pull request #163
Opened 2019-08-06 12:47 UTC by Shailin

|PR checklist|Status|
|-----|:------:|
|Is issue created in GitHub?|[Yes](https://github.com/maqsoftware/Simple-Class/issues/162)|
|Is code analysis task executed and issues resolved in the Java/Kotlin code?|NA|
|Is code analysis task executed and issues resolved in the CPP/native code?|NA|
|Is the version code set in the AndroidManifest.xml or build.gradle file to 1 more than the version which has already been published?|NA|
|Is code commenting done properly for the changes made?|NA|
|Is correct variable naming convention followed?|NA|
|Is auto formatting shortcut Ctrl+Alt+Shift+L executed in all files?|NA|
|Are the message strings used in the application taken from strings.xml file?|NA|
|Are the permissions which are not required removed from AndroidManifest.java file?|NA|
|Is the _uses-feature_ tag used for only must have feature in AndroidManifest.java file?|NA|
|Are the generated files correctly configured in .gitignore?|NA|
|Are the release signing configurations removed from the gradle files?|NA|
|Is commented code removed from all files?|NA|
|Are updated images compressed (< 100 KB)?|NA|
|Ensured there are no typos in any string. For example: Variable/method names, hardcoded strings, commit messages, PR titles, issues, code comments?|Yes|

2019-08-06 14:56 UTC, alankrutap01 commented on goa/LOCALIZE.md
> +* To build application with a new locale add a new productFlavor in ***[build.gradle](https://github.com/maqsoftware/Simple-Class/blob/master/goa/proj.android-studio/goa/build.gradle)*** file.
Add comma after locale.

2019-08-06 14:56 UTC, alankrutap01 commented on goa/LOCALIZE.md
> +* The ***[lang](https://github.com/maqsoftware/Simple-Class/tree/master/goa/Resources/res/lang/eng)*** folder contains a ***eng_en.po*** file, which contains strings in the `msgstr` tags that should
Remove 'that' after 'tags'

2019-08-06 14:56 UTC, alankrutap01 commented on goa/LOCALIZE.md
> +    * Save all the JSON files in ***[config](https://github.com/maqsoftware/Simple-Class/tree/master/goa/Resources/res/config)*** folder and append the ***lang*** code in their names for example _gra
Put full stop after 'names'

2019-08-06 14:56 UTC, alankrutap01 commented on goa/LOCALIZE.md
>  - Create a new folder under Resources/res/lang/. Lets say the folder name is xyz
'Let's' instead of 'Lets'

2019-08-06 14:56 UTC, alankrutap01 commented on goa/LOCALIZE.md
>  - In `goa/Classes/hero/RPGConfig.h` add the language like this:
Add comma after goa/Classes/hero/RPGConfig.h`

2019-08-06 14:56 UTC, alankrutap01 commented on goa/LOCALIZE.md
>  - Create a new subclass of **LangUtil** in `goa/Classes/lang/XyzUtil.cpp` like `goa/Classes/lang/SwahiliUtil.cpp`. Override each method with language specific details such as number of letters in alp
Letters in 'an' alphabet
Put full stop after 'etc'

2019-08-06 14:56 UTC, alankrutap01 commented on goa/LOCALIZE.md
>    - Record the voice over for each story and save in **Story** folder with prefix of page number. *For ex, Adhabu_Punishment/Adhabu_Punishment_0.ogg, Adhabu_Punishment/Adhabu_Punishment_1.ogg*
'Voice-over' instead of 'voice over'

2019-08-08 07:00 UTC, alankrutap01 commented on goa/LOCALIZE.md
> +* The [lang](https://github.com/maqsoftware/Simple-Class/tree/master/goa/Resources/res/lang/eng) folder contains a ***eng_en.po*** file, which contains strings in the `msgstr` tags should also be loc
Add a comma after tags

2019-08-09 11:20 UTC, ankitk20 requested changes

2019-08-09 11:20 UTC, ankitk20 commented on goa/LOCALIZE.md
> +* To build application with a new locale, add a new productFlavor in [build.gradle](https://github.com/maqsoftware/Simple-Class/blob/master/goa/proj.android-studio/goa/build.gradle) file.
`productFlavor`

2019-08-09 11:20 UTC, ankitk20 commented on goa/LOCALIZE.md
> + 	* Update the `title` in _alphabet_game_map_en.json_, _shapes_game_map_en.json_, _words_game_map_en.json_, and _writing_game_map_en.json_
Remove "the"

2019-08-09 11:20 UTC, ankitk20 commented on goa/LOCALIZE.md
> +* To build application with a new locale, add a new productFlavor in [build.gradle](https://github.com/maqsoftware/Simple-Class/blob/master/goa/proj.android-studio/goa/build.gradle) file.
To build **the** application

2019-08-09 11:20 UTC, ankitk20 commented on goa/LOCALIZE.md
> +* Add a new `localeCode` in [LevelHelpScene.h](https://github.com/maqsoftware/Simple-Class/blob/master/goa/Classes/menu/LevelHelpScene.h) file as per the build variant.
Make it "Update the locale code" instead of "Add a new locale code" as per the **desired** build variant

2019-08-09 11:20 UTC, ankitk20 commented on goa/LOCALIZE.md
> +* Update the TTS locale settings according to the new language in [VoiceMoldManager.java](https://github.com/maqsoftware/Simple-Class/blob/master/goa/proj.android-studio/goa/src/main/java/org/cocos2d
according to the new **locale** in ...

2019-08-09 11:20 UTC, ankitk20 commented on goa/LOCALIZE.md
> +* Add locale specific splash screen in [chimpleloading](https://github.com/maqsoftware/Simple-Class/tree/master/goa/Resources/res/chimpleloading) folder.
Add a splash screen image in ... folder with translated text. Also mention about OBB extraction screen

2019-08-13 10:31 UTC, ankitk20 approved these changes

2019-08-13 14:20 UTC, mathewnik90 approved these changes

2019-08-13 14:21 UTC, merged