Add support for Patch OBB.
maqsoftware/Simple-Class pull request #28
Opened 2019-06-05 07:25 UTC by jeevithiesh

2019-06-05 08:12 UTC, ankitk20 requested changes

2019-06-05 08:12 UTC, ankitk20 commented on goa/proj.android-studio/goa/src/main/java/chimple/DownloadExpansionFile.java
> +    public static final XAPKFile[] xAPKS = {
Make "s" small

2019-06-05 08:12 UTC, ankitk20 commented on goa/proj.android-studio/goa/src/main/java/chimple/DownloadExpansionFile.java
> +        ),
Press "Ctrl + Alt + L" in all the updated files

2019-06-05 08:12 UTC, ankitk20 commented on goa/proj.android-studio/goa/src/main/java/chimple/DownloadExpansionFile.java
> +        for (XAPKFile xf : xAPKS) {
Small s

2019-06-05 08:12 UTC, ankitk20 commented on goa/proj.android-studio/goa/src/main/java/chimple/DownloadExpansionFile.java
> +        mProgressPercent.setText(Long.toString(progress.mOverallProgress * 100 / progress.mOverallTotal) + "%");
Check whether "Long.toString" is required here

2019-06-05 08:12 UTC, ankitk20 commented on goa/proj.android-studio/goa/src/main/java/org/cocos2dx/cpp/AppActivity.java
> +
Remove this empty line

2019-06-05 08:12 UTC, ankitk20 commented on goa/proj.android-studio/goa/src/main/java/org/cocos2dx/cpp/AppActivity.java
> +                startActivity(intent);
Move this outside the _else_ construct and avoid code repetition

2019-06-05 08:12 UTC, ankitk20 commented on goa/proj.android-studio/goa/src/main/java/utils/Zip.java
> -            SharedPreferences.Editor editor = sharedPref.edit();
Why did you remove this?

2019-06-06 08:18 UTC, ankitk20 commented on goa/proj.android-studio/goa/src/main/java/utils/Zip.java
> +    private static int count = 0;
Why is this variable changed?

2019-06-06 08:28 UTC, ankitk20 submitted a review, later dismissed

2019-06-06 12:51 UTC, ankitk20 submitted a review, later dismissed

2019-06-07 12:11 UTC, mathewnik90 commented on goa/proj.android-studio/goa/src/main/java/chimple/DownloadExpansionFile.java
> +                    String fileName = Helpers.getExpansionAPKFileName(DownloadExpansionFile.this, xf.mIsMain, xf.mFileVersion);
Use better naming conventions

2019-06-07 12:11 UTC, mathewnik90 submitted a review, later dismissed

2019-06-07 13:02 UTC, mathewnik90 commented on goa/proj.android-studio/goa/src/main/java/org/cocos2dx/cpp/AppActivity.java
> +        String flagFilePath = "/storage/emulated/0/Android/data/com.maq.xprize.chimple.hindi/files/.success.txt";
Use getPackageName

2019-06-07 13:04 UTC, mathewnik90 commented on goa/proj.android-studio/goa/src/main/java/org/cocos2dx/cpp/SplashScreenActivity.java
> +        ZipFile zipFile;
Use better variable names

2019-06-07 14:21 UTC, ankitk20 submitted a review, later dismissed

2019-06-07 14:40 UTC, mathewnik90 approved these changes

2019-06-07 14:41 UTC, merged