Optimize the Java code after running code quality check.
maqsoftware/Simple-Class pull request #41
Opened 2019-06-10 12:49 UTC by jeevithiesh

2019-06-11 12:03 UTC, ankitk20 requested changes

2019-06-11 12:03 UTC, ankitk20 commented on goa/proj.android-studio/downloader_library/src/main/java/com/google/android/vending/expansion/downloader/impl/DownloadThread.java
> +//     */
Why single line comment if there is already a multi-line comment?

2019-06-11 12:03 UTC, ankitk20 commented on goa/proj.android-studio/downloader_library/src/main/java/com/google/android/vending/expansion/downloader/impl/DownloadThread.java
> +            wakeLock.acquire(10*60*1000L /*10 minutes*/);
Put the comment outside the method parameter

2019-06-11 12:03 UTC, ankitk20 commented on goa/proj.android-studio/goa/src/main/java/com/maq/xprize/bali/provider/LessonContentProvider.java
>  //                application.updateCoinNotifications("Coins:", coinMessage, updatedCoins);
Remove this commented code as well

2019-06-11 12:03 UTC, ankitk20 commented on goa/proj.android-studio/goa/src/main/java/com/maq/xprize/bali/service/ServiceRunnable.java
> +//     */
Is single line comment necessary?

2019-06-11 12:03 UTC, ankitk20 commented on goa/proj.android-studio/goa/src/main/res/values/strings.xml
> +    <string name="_0">0 %</string>
Replace "_0" with "start_percent"

2019-06-11 12:03 UTC, ankitk20 commented on goa/proj.android-studio/goa/src/main/res/values/strings.xml
> +    <string name="button_scan">Scan</string>
I think these are not required anymore. Check once again.

2019-06-11 12:14 UTC, jeevithiesh commented on goa/proj.android-studio/downloader_library/src/main/java/com/google/android/vending/expansion/downloader/impl/DownloadThread.java
> +//     */
The Android lint gave an error for @return in the comment. I just thought it would be better to eliminate the error as this doesn't effect the code

2019-06-11 12:22 UTC, jeevithiesh commented on goa/proj.android-studio/goa/src/main/java/com/maq/xprize/bali/service/ServiceRunnable.java
> +//     */
The Android lint gave an error for @param in the comment. I just thought it would be better to eliminate the error as this doesn't effect the code

2019-06-11 13:14 UTC, jeevithiesh commented on goa/proj.android-studio/goa/src/main/res/values/strings.xml
> +    <string name="button_scan">Scan</string>
I have removed them.

2019-06-11 13:15 UTC, jeevithiesh commented on goa/proj.android-studio/goa/src/main/res/values/strings.xml
> +    <string name="_0">0 %</string>
I have changed it.

2019-06-11 13:15 UTC, jeevithiesh commented on goa/proj.android-studio/goa/src/main/java/com/maq/xprize/bali/provider/LessonContentProvider.java
>  //                application.updateCoinNotifications("Coins:", coinMessage, updatedCoins);
I have removed it.

2019-06-11 13:15 UTC, jeevithiesh commented on goa/proj.android-studio/downloader_library/src/main/java/com/google/android/vending/expansion/downloader/impl/DownloadThread.java
> +            wakeLock.acquire(10*60*1000L /*10 minutes*/);
I moved the comment outside the method.

2019-06-13 10:27 UTC, ankitk20 requested changes

2019-06-13 10:27 UTC, ankitk20 commented on goa/proj.android-studio/downloader_library/src/main/java/com/google/android/vending/expansion/downloader/impl/DownloadThread.java
> +//     */
Remove single line comments

2019-06-13 10:27 UTC, ankitk20 commented on goa/proj.android-studio/goa/src/main/java/com/maq/xprize/bali/service/ServiceRunnable.java
> +//     */
Remove this

2019-06-18 04:21 UTC, closed without merging